services:

##########################################
##
## public / network infrastructure
##
##########################################

    public-vpn-server:

        container_name: public-vpn-server
        
        image: kylemanna/openvpn

        restart: unless-stopped
                
        cap_add:

            - NET_ADMIN       

        volumes:

            - /volumes/intranet/openvpn:/etc/openvpn

        ports:

            - "1194:1194/udp"

    public-vpn-docs:

        container_name: public-vpn-docs

        image: softwareshinobi/embanet-intranet-docs

        build: 

            context: docs

            dockerfile: Dockerfile
      
        restart: unless-stopped
  
        ports:

            - "1180:80"

##########################################
##
## private / identity & access managment
##
##########################################

    public-vpn-proxy:

        container_name: public-vpn-proxy

        image: softwareshinobi/basic-container-auth-proxy

        restart: unless-stopped

        ports:

            - 1194:80

        environment:
            
##            BASIC_AUTH_USERNAME: shinobi
##
##            BASIC_AUTH_PASSWORD: password

            PROXY_PASS: http://private-vpn-keys/

    private-vpn-keys:

        container_name: private-vpn-keys
        
        image: softwareshinobi/embanet-intranet-keys

        restart: unless-stopped

        build: 

            context: publisher

            dockerfile: Dockerfile
      
        volumes:

            - /volumes/intranet/openvpn/:/usr/share/nginx/html/keys/

        ports:

            - "127.0.0.1:1188:80"
            
            - "10.28.1.1:1188:80"

##########################################
##
## intranet services / accessible on VPS only
##
##########################################

    private-intranet-landing:

        container_name: private-intranet-landing

        image: softwareshinobi/embanet-intranet-landing

        build: 

            context: landing

            dockerfile: Dockerfile
 
        restart: unless-stopped
  
        ports:

            - "127.0.0.1:80:80"
            
            - "10.28.1.1:80:80"        
